version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-ap-southeast-2-786338495378 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml
