version: 0.2
phases:
  install:
    commands:
      - dotnet publish -c Release
      - aws cloudformation package --template-file template.yaml --s3-bucket reporterbotdeploymentbucket --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - src/PRTG/bin/Release/netcoreapp2.1/publish/*
    - template.yaml
    - outputSamTemplate.yaml
# https://aws.amazon.com/blogs/compute/developing-net-core-aws-lambda-functions/